In [1]:
import numpy as np

In [2]:
def read_matrix_from_binary_file(filename, is_vec = False):
    with open(filename, "rb") as f:
        # Read the number of rows and columns
        rows = int.from_bytes(f.read(4), byteorder='little', signed=True)

        if is_vec:
            # If it's a vector, read only one dimension
            cols = 1
        else:
            # Read the number of columns
            cols = int.from_bytes(f.read(4), byteorder='little', signed=True)

        print(rows, cols)
        
        # Read the matrix data
        data = np.fromfile(f, dtype=np.float64)
        return data.reshape((rows, cols))

In [3]:
nrows = 117
ncols = 27

# Example usage
filename = f"inputs/input_matrix_{nrows:04d}_{ncols:04d}.bin"
matrix = read_matrix_from_binary_file(filename)
print(matrix[:5, :5])  # Print the first 5x5 submatrix

117 27
[[716.236 121.206   8.772 848.215 948.018]
 [122.665 280.082 576.706 138.008 202.077]
 [302.282 569.491 850.162 135.74  231.794]
 [659.701  47.381 781.684 207.185 976.312]
 [382.885 944.48  805.979 315.417  27.85 ]]


In [14]:
# Read correct outputs
filename = f"correct_output/u_{nrows:04d}_{ncols:04d}.bin"
corr_U = read_matrix_from_binary_file(filename)

filename = f"correct_output/v_{nrows:04d}_{ncols:04d}.bin"
corr_V = read_matrix_from_binary_file(filename)

# Read the correct singular values
filename = f"correct_output/singular_{nrows:04d}_{ncols:04d}.bin"
corr_S = read_matrix_from_binary_file(filename, is_vec=True)

117 117
27 27
27 1


In [15]:
print(corr_S[:5])  # Print the first 5 singular values

[[3.30698739e+10]
 [3.19125196e+10]
 [1.27506927e+10]
 [1.24023157e+10]
 [1.22885888e+10]]


In [11]:
# Read program's outputs
filename = f"prog_output/U_{nrows:04d}_{ncols:04d}.bin"
prog_U = read_matrix_from_binary_file(filename)

filename = f"prog_output/V_{nrows:04d}_{ncols:04d}.bin"
prog_V = read_matrix_from_binary_file(filename)

# Read the program's singular values
filename = f"prog_output/S_{nrows:04d}_{ncols:04d}.bin"
prog_S = read_matrix_from_binary_file(filename)

117 117
27 27
117 27


In [12]:
print(prog_S[:5, :5])  # Print the first 5 singular values

[[28014.76579201     0.             0.             0.
      0.        ]
 [    0.          4465.28737014     0.             0.
      0.        ]
 [    0.             0.          4322.17020976     0.
      0.        ]
 [    0.             0.             0.          4016.90754139
      0.        ]
 [    0.             0.             0.             0.
   3993.46813958]]


In [13]:
# Perform svd using numpy
U, S, Vt = np.linalg.svd(matrix, full_matrices=True)

# Print first 5 singular values
print(S[:5])  # Print the first 5 singular values

[28014.76579201  4465.28737018  4322.17020974  4016.90754154
  3993.46813944]


In [16]:
prog_U[:5, :5]

array([[-1.06846323e-01, -4.92389697e-02, -7.23506786e-02,
        -1.13189861e-01,  1.81242523e-01],
       [-8.39902450e-02, -7.53766595e-02,  1.38493725e-01,
        -1.05926937e-01, -1.16392255e-01],
       [-8.23335033e-02,  5.18253212e-02,  1.18821503e-01,
         1.20989488e-01,  1.10596614e-01],
       [-7.97528659e-02, -2.15161071e-01, -5.94320175e-02,
         8.84358698e-03,  1.35323044e-04],
       [-1.04663882e-01, -9.77196597e-02,  5.20440619e-02,
         1.01391181e-01,  1.44117490e-01]])

In [17]:
U[:5, :5]

array([[-1.06846322e-01,  4.92400828e-02,  7.23492745e-02,
        -1.13205652e-01, -1.81233398e-01],
       [-8.39902453e-02,  7.53745514e-02, -1.38495560e-01,
        -1.05916231e-01,  1.16400843e-01],
       [-8.23335042e-02, -5.18271290e-02, -1.18819937e-01,
         1.20980891e-01, -1.10604768e-01],
       [-7.97528508e-02,  2.15161984e-01,  5.94287861e-02,
         8.84318269e-03, -1.38122759e-04],
       [-1.04663870e-01,  9.77188734e-02, -5.20448925e-02,
         1.01379323e-01, -1.44124871e-01]])