In [1]:
import numpy as np

In [2]:
def read_matrix_from_binary_file(filename, is_vec = False):
    with open(filename, "rb") as f:
        # Read the number of rows and columns
        rows = int.from_bytes(f.read(4), byteorder='little', signed=True)

        if is_vec:
            # If it's a vector, read only one dimension
            cols = 1
        else:
            # Read the number of columns
            cols = int.from_bytes(f.read(4), byteorder='little', signed=True)

        print(rows, cols)
        
        # Read the matrix data
        data = np.fromfile(f, dtype=np.float64)
        return data.reshape((rows, cols))

In [12]:
nrows = 934
ncols = 612

# Example usage
filename = f"inputs/input_matrix_{nrows:04d}_{ncols:04d}.bin"
matrix = read_matrix_from_binary_file(filename)
print(matrix[:5, :5])  # Print the first 5x5 submatrix

934 612
[[622.579 366.623 132.207 573.919  32.971]
 [824.172 332.353 532.993 136.763 398.53 ]
 [980.526 427.364 852.104   5.466 209.072]
 [ 35.09  563.094  69.523 958.321 106.659]
 [580.121  24.634 733.86  894.155 530.408]]


In [13]:
# Read correct outputs
filename = f"correct_output/u_{nrows:04d}_{ncols:04d}.bin"
corr_U = read_matrix_from_binary_file(filename)

filename = f"correct_output/v_{nrows:04d}_{ncols:04d}.bin"
corr_V = read_matrix_from_binary_file(filename)

# Read the correct singular values
filename = f"correct_output/singular_{nrows:04d}_{ncols:04d}.bin"
corr_S = read_matrix_from_binary_file(filename, is_vec=True)

934 934
612 612
612 1


In [14]:
print(corr_S[:5])  # Print the first 5 singular values

[[5.78614774e+11]
 [5.88222130e+10]
 [5.85987311e+10]
 [5.80225128e+10]
 [5.76751566e+10]]


In [15]:
# Read program's outputs
filename = f"prog_output/U_{nrows:04d}_{ncols:04d}.bin"
prog_U = read_matrix_from_binary_file(filename)

filename = f"prog_output/V_{nrows:04d}_{ncols:04d}.bin"
prog_V = read_matrix_from_binary_file(filename)

# Read the program's singular values
filename = f"prog_output/S_{nrows:04d}_{ncols:04d}.bin"
prog_S = read_matrix_from_binary_file(filename, is_vec=True)

934 934
612 612
612 1


In [16]:
print(prog_S[:5])  # Print the first 5 singular values

[[379334.78183423]
 [     0.        ]
 [     0.        ]
 [     0.        ]
 [     0.        ]]


In [19]:
np.unique(prog_S)

array([     0.        , 379334.78183423])